#!/bin/bash
# This is a comment

docker run -p 8081:80 -v ${PWD}/default.conf:/etc/nginx/conf.d/default.conf -v ${PWD}/505.html:/var/www/errors/505.html  -v ${PWD}/html/:/usr/share/nginx/html/:ro nginx
