version: '3'
services:
        sshd:
                image: sshd
                container_name: pless
                build: .
                restart: always
                ports: 
                - "0.0.0.0:2222:22"
